# Generated by Django 4.2.5 on 2023-10-26 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='additional_information',
            field=models.TextField(blank=True, default='more info', null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='being_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
